#include "gagregrog.h"
#include "tap_dances.h"
#include "keymap.h"

// - All Tap Dances

tap_dance_action_t tap_dance_actions[] = {
  [T_L1_K1]  = ACTION_TAP_DANCE_GAGREGROG(td_handle_L1_K1),
  [T_L1_K2]  = ACTION_TAP_DANCE_GAGREGROG(td_handle_L1_K2),
  [T_L2_K1]  = ACTION_TAP_DANCE_GAGREGROG(td_handle_L2_K1),
  [T_L2_K2]  = ACTION_TAP_DANCE_GAGREGROG(td_handle_L2_K2),
};

// L1_K1
static td_actions_gagregrog_t actions_L1_K1[] = {
  UNICODE__TD_ACTION_GAGREGROG(FIRE),
  LAYER__TD_ACTION_GAGREGROG(L2),
  UNICODE__TD_ACTION_GAGREGROG(FIRE, 2),
  UNICODE__TD_ACTION_GAGREGROG(MIDDLE_FINGER),
  UNICODE__TD_ACTION_GAGREGROG(FIRE, 10),
  UNICODE__TD_ACTION_GAGREGROG(MIDDLE_FINGER, 10),
};
void td_handle_L1_K1(TD_ARGS_GAGREGROG) {
  HANDLE_TAP_DANCE_GAGREGROG(actions_L1_K1);
}

// L1_K2
static td_actions_gagregrog_t actions_L1_K2[] = {
  UNICODE__TD_ACTION_GAGREGROG(SKULL),
  LAYER__TD_ACTION_GAGREGROG(L2),
  UNICODE__TD_ACTION_GAGREGROG(SKULL, 2),
  UNICODE__TD_ACTION_GAGREGROG(PREGNANT_MAN),
  UNICODE__TD_ACTION_GAGREGROG(SKULL, 10),
  UNICODE__TD_ACTION_GAGREGROG(PREGNANT_MAN, 10),
};
void td_handle_L1_K2(TD_ARGS_GAGREGROG) {
  HANDLE_TAP_DANCE_GAGREGROG(actions_L1_K2);
}

// L2_K1
static td_actions_gagregrog_t actions_L2_K1[] = {
  UNICODE__TD_ACTION_GAGREGROG(CAT),
  UNICODE__TD_ACTION_GAGREGROG(SUNGLASSES),
  UNICODE__TD_ACTION_GAGREGROG(CAT, 2),
  UNICODE__TD_ACTION_GAGREGROG(SUNGLASSES, 2),
  UNICODE__TD_ACTION_GAGREGROG(CAT, 10),
  UNICODE__TD_ACTION_GAGREGROG(SUNGLASSES, 10),
};
void td_handle_L2_K1(TD_ARGS_GAGREGROG) {
  HANDLE_TAP_DANCE_GAGREGROG(actions_L2_K1);
}

// L2_K2
static td_actions_gagregrog_t actions_L2_K2[] = {
  UNICODE__TD_ACTION_GAGREGROG(SHOUT),
  UNICODE__TD_ACTION_GAGREGROG(SHOUT, 10),
  UNICODE_STRING__TD_ACTION_GAGREGROG("🗣️🔥"),
  UNICODE_STRING__TD_ACTION_GAGREGROG("💀🫃😎🖕😼"),
  NULL__TD_ACTION_GAGREGROG,
  NULL__TD_ACTION_GAGREGROG,
  NULL__TD_ACTION_GAGREGROG,
  NULL__TD_ACTION_GAGREGROG,
  NULL__TD_ACTION_GAGREGROG,
  FN__TD_ACTION_GAGREGROG(unicode_input_mode_step),
};
void td_handle_L2_K2(TD_ARGS_GAGREGROG) {
  HANDLE_TAP_DANCE_GAGREGROG(actions_L2_K2);
}
