TRACKPOINT_ENABLE = yes
POINTING_DEVICE_INVERT_SCROLL = yes

COMMAND_ENABLE = no
RGBLIGHT_ENABLE = yes
AUTO_SHIFT_ENABLE = no
LTO_ENABLE = yes
MOUSE_TURBO_CLICK = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
